/* strings */

export const DEFAULT_TEXT_BASE64 = 'LS0tJTBB';
export const DEFAULT_TEXT = '---\n';
export const DEFAULT_TITLE = 'title';
export const NOW_DOC_ID = 'now-doc-id';
export const DOC_TITLE = 'doc-title';
export const DOC_TEXT = 'doc-text';
export const LOCAL_KEY = 'bluetang';
export const HELP_PAGE_URL = 'https://github.com/SeonJun-Hwang/bluetang/wiki';
export const BLUE_TANG_TO_MARP_FIRST_PAGE = `---
marp: true
---
# title
### Generated by Blue tang Presenter
#### for VS Code
`;

/* numbers */
export const DEBOUNCE_INTERVAL = 200;

/* objects */
export const KEY_STR = {
  F5: 'F5',
  LEFT: 'ArrowLeft',
  RIGHT: 'ArrowRight',
};
